### ISSUE TITLE
Listed example does not function

### ISSUE THREAD

**Issue by redcap3000** [snapcard/snapcard-node#1]
```
 requestOptions.qs = Object.assign(requestOptions.qs, params);
                                       ^
TypeError: undefined is not a function
    at assembleRequestOptions (/Users/redcap/snapcardTest/node_modules/snapcard/lib/snapcard.js:48:40)
    at Snapcard.invoke (/Users/redcap/snapcardTest/node_modules/snapcard/lib/snapcard.js:20:30)
    at Object.<anonymous> (/Users/redcap/snapcardTest/test.js:6:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I tried running the example on the README.md and ran across this error. Running node v0.12.4

**Comment by redcap3000** [comment]
Also Promise is incompatible.. Would it be possible to offer a version that works in older versions of node? It is often an unrealistic request to run the version of node that these implementations require in production settings.

**Comment by jordanluyke** [comment]
@redcap3000 let me know if the new release works for you, thanks

**Comment by redcap3000** [comment]
Yes I am no longer receiving those errors. Thanks!
